import ts from 'typescript';
import {writeFile,mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
import {join} from 'node:path';
import assert from 'node:assert/strict';
const dir=await mkdtemp(join(tmpdir(),'soando-test-'));
const counts=new Map();
const DB={prepare(sql){return {bind(...v){return {async run(){if(sql.startsWith('DELETE'))return {};if(counts.has(v[0]))return {meta:{changes:0}};counts.set(v[0],1);return {meta:{changes:1}}},async first(){const n=counts.get(v[0])||0;if(n>=v[2])return null;counts.set(v[0],n+1);return {count:n+1}}}}}}};
globalThis.soandoTestEnv={DB};
for(const [src,dest] of [['lib/coach.ts','coach.mjs'],['lib/runtime.ts','runtime.mjs'],['app/api/coach/route.ts','route.mjs']]){let source=await readFile(src,'utf8');source=source.replace("from 'zod'",`from ${JSON.stringify(require.resolve('zod'))}`).replace("import { env } from 'cloudflare:workers';","const env=globalThis.soandoTestEnv;").replace("@/lib/runtime","./runtime.mjs").replace("@/lib/coach","./coach.mjs");await writeFile(join(dir,dest),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText)}
const {POST,OPTIONS}=await import(join(dir,'route.mjs'));
globalThis.soandoTestEnv.APP_ORIGIN='https://frommars-teacher.github.io';
assert.equal((await OPTIONS(new Request('https://example.com/api/coach',{headers:{Origin:'https://frommars-teacher.github.io'}}))).status,204);
assert.equal((await OPTIONS(new Request('https://example.com/api/coach',{headers:{Origin:'https://untrusted.example'}}))).status,403);
let calls=0;const actualFetch=globalThis.fetch;let ai={};globalThis.fetch=async()=>{calls++;return Response.json({choices:[{message:{content:JSON.stringify(ai)}}]})};
const payload=(extra={})=>({operation:'evaluate',lyrics:'소안도의 바람 속에\n기억하는 우리 마음',code:'class-test',session:crypto.randomUUID(),requestId:crypto.randomUUID(),...extra});
const req=b=>new Request('https://example.com/api/coach',{method:'POST',headers:{Origin:'https://example.com','Content-Type':'application/json'},body:JSON.stringify(b)});
const closed=await POST({get body(){throw Error('Body must not be read')}});assert.equal(closed.status,503);assert.equal(calls,0);
Object.assign(globalThis.soandoTestEnv,{OPENAI_API_KEY:'test-placeholder',STUDENT_AI_ENABLED:'true',ZDR_VERIFIED:'true',POLICY_REVIEWED:'true',CLASSROOM_CODE:'class-test',DAILY_REQUEST_LIMIT:'100'});
assert.equal((await POST(req(payload({code:'wrong'})))).status,403);
assert.equal((await POST(req(payload({lyrics:'x'.repeat(3001)})))).status,400);
assert.equal((await POST(req(payload({lyrics:'연락처는 010-1234-5678 입니다'})))).status,400);
assert.equal((await POST(req(payload({operation:'ocr',image:'data:text/html;base64,eA=='})))).status,400);
const c={grade:'좋아요',strength:'장점',improvement:'제안',quote:'소안도의 바람',explanation:'근거'};
ai={form:c,content:c,rhythm:c,priority:'한 줄 다듬기',revisedLyrics:'소안도의 바람 속에\n기억하는 우리 마음',changes:[],reasons:['표현을 살렸어요','마음을 유지했어요'],factChecks:[]};
const b=payload();assert.equal((await POST(req(b))).status,200);assert.equal((await POST(req(b))).status,409);
const before=calls;ai={...ai,form:{...c,quote:'학생이 쓰지 않은 문장'}};assert.equal((await POST(req(payload()))).status,502);assert.equal(calls,before+1);
ai={text:'소안도의 바람\n\n우리의 마음',uncertain:['한 글자 확인']};assert.equal((await POST(req(payload({operation:'ocr',image:'data:image/jpeg;base64,/9j/'})))).status,200);
ai={...c};assert.equal((await POST(req(payload()))).status,502);
counts.clear();ai={form:c,content:c,rhythm:c,priority:'한 줄 다듬기',revisedLyrics:'소안도의 바람 속에\n기억하는 우리 마음',changes:[],reasons:['표현 유지','감정 유지'],factChecks:[]};
const session=crypto.randomUUID();for(let i=0;i<12;i++)assert.equal((await POST(req(payload({session})))).status,200);assert.equal((await POST(req(payload({session})))).status,429);
counts.clear();globalThis.soandoTestEnv.DAILY_REQUEST_LIMIT='8';const concurrent=await Promise.all(Array.from({length:20},()=>POST(req(payload()))));assert.equal(concurrent.filter(r=>r.status===200).length,8);assert.equal(concurrent.filter(r=>r.status===429).length,12);
counts.clear();globalThis.fetch=async()=>{throw new Error('network')};assert.equal((await POST(req(payload()))).status,502);
globalThis.fetch=actualFetch;await rm(dir,{recursive:true});console.log('PASS: closed gate before body read; validation; private data pattern; duplicate request; schema/quotation grounding; mock OCR; session quota; 20 concurrent mocked requests; network failure. No real AI called.');
