'use client';
import {useEffect,useRef,useState} from 'react';
import {Music2,Camera,Upload,FileText,Check,Copy,ExternalLink,RotateCcw,ShieldCheck,LoaderCircle} from 'lucide-react';
import type {Evaluation} from '@/lib/coach';
import {basicCheck,type QuickTip} from '@/lib/basic-check';
import {AnnotatedReview} from '@/components/annotated-review';
import {apiUrl,teacherUrl} from '@/lib/frontend';
const steps=['가사 입력','가사 점검','가사 다듬기','가사 완성'];
export default function Studio(){
 const [step,setStep]=useState(0),[mode,setMode]=useState('text'),[lyrics,setLyrics]=useState(''),[original,setOriginal]=useState(''),[final,setFinal]=useState(''),[intent,setIntent]=useState(''),[mood,setMood]=useState(''),[code,setCode]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[result,setResult]=useState<Evaluation|null>(null),[uncertain,setUncertain]=useState<string[]>([]),[confirmed,setConfirmed]=useState(true),[restored,setRestored]=useState(false);
 const [quickTips,setQuickTips]=useState<Record<'form'|'content'|'rhythm',QuickTip>|null>(null);
 const [basicScores,setBasicScores]=useState<number[]|null>(null);
 function checkBasicText(text:string){try{const checked=basicCheck(text);setBasicScores(checked.scores);setQuickTips(checked.tips);setLyrics(text);setOriginal(text);setFinal(text);setResult(checked.result);setStep(1);setMessage('기본 점검을 마쳤어요. 가사는 외부로 전송하지 않았어요.');return true}catch(e){setMessage(e instanceof Error?e.message:'가사를 확인해 주세요.');return false}}
 function checkBasic(){checkBasicText(lyrics)}
 const lock=useRef(false),file=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const d=JSON.parse(sessionStorage.getItem('soando-draft')||'null');if(d){setLyrics(d.lyrics||'');setFinal(d.final||'');setMessage('이 탭에서 쓰던 가사를 불러왔어요.')}}catch{}setRestored(true);fetch(apiUrl('/api/status')).then(r=>r.json()).then(d=>setReady((d as {enabled:boolean}).enabled)).catch(()=>setReady(false))},[]);
 useEffect(()=>{if(restored)try{sessionStorage.setItem('soando-draft',JSON.stringify({lyrics,final}))}catch{}},[lyrics,final,restored]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(lyrics||final){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[lyrics,final]);
 async function request(operation:string,extra:object){if(lock.current)return;lock.current=true;setBusy(operation);setMessage('');try{let session=sessionStorage.getItem('soando-session');if(!session){session=crypto.randomUUID();sessionStorage.setItem('soando-session',session)}const r=await fetch(apiUrl('/api/coach'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation,...extra,code,session,requestId:crypto.randomUUID()}),signal:AbortSignal.timeout(65000)});const d=await r.json() as {error?:string;result:Evaluation & {text:string;uncertain:string[]}};if(!r.ok)throw Error(d.error||'연결을 확인해 주세요.');if(operation==='ocr'){setLyrics(d.result.text);setUncertain(d.result.uncertain);setConfirmed(false);setMessage('인식한 글을 확인하고 수정한 뒤 확인 버튼을 눌러 주세요.')}else{setBasicScores(null);setQuickTips(null);setOriginal(lyrics);setFinal(lyrics);setResult(d.result);setStep(1)}}catch(e){setMessage(e instanceof Error?e.message:'다시 시도해 주세요.')}finally{setBusy('');lock.current=false}}
 async function image(f?:File){if(!f)return;if(!ready){setMessage('사진 인식은 선생님의 AI 설정이 완료되면 사용할 수 있어요.');return}if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>8*1024*1024){setMessage('8MB 이하의 JPG, PNG, WebP 사진을 선택해 주세요.');return}try{const bitmap=await createImageBitmap(f);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const c=document.createElement('canvas');c.width=Math.round(bitmap.width*scale);c.height=Math.round(bitmap.height*scale);c.getContext('2d')!.drawImage(bitmap,0,0,c.width,c.height);bitmap.close();await request('ocr',{image:c.toDataURL('image/jpeg',.85)})}catch{setMessage('사진을 읽지 못했어요. 다른 사진을 선택하거나 직접 입력해 주세요.')}}
 async function copy(){try{await navigator.clipboard.writeText(final);setMessage('최종 가사를 복사했어요.')}catch{setMessage('자동 복사를 못 했어요. 가사를 길게 누르거나 전체 선택하여 복사해 주세요.')}}
 function reset(){if(!window.confirm('이 탭의 가사를 지우고 새로 시작할까요?'))return;setLyrics('');setFinal('');setResult(null);setBasicScores(null);setQuickTips(null);setStep(0);setUncertain([]);setConfirmed(true);setMessage('새 노랫말을 시작해요.');sessionStorage.removeItem('soando-draft')}
 return <main><header><a className="brand" href="./" aria-label="소안도의 노래 홈"><span className="logo"><Music2 size={23}/></span><span>소안도의 노래<small>독서에서 시작하는 작사 스튜디오</small></span></a><span className="studio-label">『소안도』 · 나의 노랫말</span><button className="quiet" onClick={reset}><RotateCcw size={16}/><span>새로 시작</span></button></header>
 <section className="intro"><span className="eyebrow">소안도에서 시작된 이야기</span><h1>역사를 기억하고,<br className="mobile"/> 우리의 마음을 노래하다.</h1><p>『소안도』를 읽고 느낀 마음을, 나만의 노랫말로 남겨 보세요.</p></section>
 <nav className="steps" aria-label="학습 진행 단계">{steps.map((s,i)=><button key={s} disabled={!!busy||(i===1||i===2)&&!result} onClick={()=>{if(i===1&&basicScores&&final!==original){checkBasicText(final);return}if(i===3&&!final)setFinal(lyrics);setStep(i)}} aria-current={step===i?'step':undefined} className={step===i?'active':step>i?'done':''}><span>{step>i?<Check size={16}/>:String(i+1).padStart(2,'0')}</span><b>{s}</b></button>)}</nav>
 {!ready&&<div className="notice"><ShieldCheck size={20}/><div><strong>기본 가사 점검은 바로 사용할 수 있어요.</strong><p>행·연·음절·주제 낱말을 이 기기에서 확인해요. AI 평가와 사진 인식은 아직 연결되지 않았어요.</p></div></div>}
 <div className="workspace"><aside><span className="eyebrow">작업 {String(step+1).padStart(2,'0')}</span><h2>{['내 마음을<br/>가사에 담기','노랫말을<br/>다시 들여다보기','제안을 살펴보고<br/>내가 선택하기','나만의<br/>노랫말 완성'][step].split('<br/>').map((t,i)=><span key={t}>{i>0&&<br/>}{t}</span>)}</h2><p>{['잘 쓰려고 서두르지 않아도 괜찮아요. 책에서 기억에 남은 장면과 마음부터 써 보세요.','잘한 부분과 다듬을 부분을 읽어 보세요. 점검 결과가 내 생각과 맞는지도 살펴보세요.','점검 결과는 정답이 아니에요. 내 표현을 살릴지, 바꿀지는 내가 결정해요.','단어와 줄바꿈을 마지막으로 확인하고, 소리 내어 읽어 보세요.'][step]}</p><div className="side-note"><span>내 가사 노트</span><dl><div><dt>분량</dt><dd>{(step>=2?final:lyrics).length.toLocaleString()}자</dd></div><div><dt>행</dt><dd>{(step>=2?final:lyrics).split('\n').filter(x=>x.trim()).length}행</dd></div><div><dt>연</dt><dd>{(step>=2?final:lyrics).trim()?(step>=2?final:lyrics).trim().split(/\n\s*\n/).length:0}연</dd></div></dl><p>연의 수와 길이는 자유롭게.<br/>내 목소리에 맞게 써 보세요.</p></div></aside>
 <section className="panel">
 {step===0&&<><div className="panel-title"><h3>내 가사 입력하기</h3><span>01 / 04</span></div><div className="tabs"><button className={mode==='text'?'selected':''} onClick={()=>setMode('text')}><FileText size={18}/> 직접 입력</button><button className={mode==='photo'?'selected':''} onClick={()=>setMode('photo')}><Camera size={18}/> 손글씨 사진</button></div>
 {mode==='photo'&&<div className="upload"><Upload size={26}/><strong>가사만 보이도록 찍어 주세요.</strong><p>얼굴, 이름, 학번, 연락처가 담긴 사진은 올리지 마세요.<br/>JPG · PNG · WebP / 최대 8MB</p><div className="actions"><button disabled={!ready||!!busy} onClick={()=>camera.current?.click()}><Camera size={16}/> 사진 찍기</button><button disabled={!ready||!!busy} onClick={()=>file.current?.click()}><Upload size={16}/> 파일 선택</button></div><input ref={file} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void image(e.target.files?.[0]);e.target.value=''}}/><input ref={camera} hidden type="file" capture="environment" accept="image/*" onChange={e=>{void image(e.target.files?.[0]);e.target.value=''}}/></div>}
 <label htmlFor="lyrics" className="field-label">{mode==='photo'?'인식한 가사 확인·수정':'내가 쓴 노랫말'}<span>{lyrics.length.toLocaleString()} / 3,000자</span></label><textarea id="lyrics" value={lyrics} maxLength={3000} disabled={!!busy} onChange={e=>setLyrics(e.target.value)} placeholder={'책을 읽고 떠오른 마음을 여기에 써 주세요.\n\n연과 연 사이는 한 줄 띄워도 좋아요.'}/>
 {!!uncertain.length&&<div className="warning">확인이 필요한 글자{uncertain.map((t,i)=><p key={i}>{t}</p>)}</div>}{!confirmed&&<button className="confirm" onClick={()=>{setConfirmed(true);setMessage('확인한 가사로 평가받을 수 있어요.')}}>인식한 가사를 확인했어요</button>}
 <div className="options"><fieldset><legend>노래에 담고 싶은 마음 <small>선택</small></legend>{['항일 의지','감사와 존경','희생과 기억','자유롭게 표현'].map(x=><button key={x} aria-pressed={intent===x} className={intent===x?'chip chosen':'chip'} onClick={()=>setIntent(intent===x?'':x)}>{x}</button>)}</fieldset><fieldset><legend>노래의 분위기 <small>선택</small></legend>{['웅장하게','감동적으로','힘차게','잔잔하게'].map(x=><button key={x} aria-pressed={mood===x} className={mood===x?'chip chosen':'chip'} onClick={()=>setMood(mood===x?'':x)}>{x}</button>)}</fieldset></div>
 {ready&&<label className="code">수업 코드 <input autoComplete="off" type="password" value={code} onChange={e=>setCode(e.target.value)} placeholder="선생님이 알려 준 코드"/></label>}<p className="privacy">이름이나 개인정보는 쓰지 마세요. 초안은 이 브라우저 탭에서 임시 보관해요.</p><button className="secondary full" disabled={!!busy||lyrics.trim().length<2||!confirmed} onClick={checkBasic}>기본 가사 점검받기</button>{ready&&<button className="primary full" disabled={!ready||!!busy||lyrics.trim().length<10||!confirmed||!code} onClick={()=>request('evaluate',{lyrics,intent,mood})}>{busy?<LoaderCircle className="spin" size={19}/>:<Music2 size={19}/>} {busy?'AI 작사 코치가 읽고 있어요…':'AI 작사 코치에게 평가받기'}</button>}{!ready&&<button className="secondary full" disabled={!lyrics.trim()} onClick={()=>{setFinal(lyrics);setStep(3)}}>내가 직접 다듬어 완성하기</button>}</>}
 {step===1&&result&&<><div className="panel-title"><h3>내 가사에 붙인 피드백</h3><span>02 / 04</span></div>{quickTips&&basicScores?<AnnotatedReview text={original} tips={quickTips} result={result} scores={basicScores} onApply={text=>{if(text.length>3000)return false;setFinal(text);setLyrics(text);setMessage('선택한 행을 고쳤어요. 수정한 부분을 확인해 주세요.');return true}} onRecheck={checkBasicText} onEdit={()=>setStep(2)}/>:<><div className="cards compact-cards">{([['form','형식 · 줄 나누기'],['content','내용 · 마음 전하기'],['rhythm','운율 · 부르기 좋게']] as const).map(([k,title])=><article className="evaluation quick-card" key={k}><div><h4>{title}</h4><span className={'grade g'+(['좋아요','조금 다듬어 봐요','보완이 필요해요'].indexOf(result[k].grade))}>{result[k].grade}</span></div>{quickTips?<><span className="target-label">{quickTips[k].line}행 · {quickTips[k].keep?'살릴 가사':'살펴볼 가사'}</span><blockquote>{quickTips[k].quote}</blockquote><p className="quick-action">{quickTips[k].action}</p>{quickTips[k].example&&<div className="tip-example"><b>이렇게 해 볼 수 있어요</b><pre>{quickTips[k].example}</pre></div>}</>:<><blockquote>{result[k].quote}</blockquote><p className="quick-action">{result[k].improvement}</p></>}<details className="check-details"><summary>점검 기준{basicScores?` · 기본 지표 ${basicScores[k==='form'?0:k==='content'?1:2]}/100`:''}</summary><p>{result[k].strength}</p><p>{result[k].explanation}</p></details></article>)}</div><div className="priority"><span>먼저 해 볼 한 가지</span><p>{result.priority}</p></div>{basicScores?<p className="caption">낱말과 줄 길이를 살핀 참고 의견이에요. 역사적 사실은 책과 확인해 주세요.</p>:result.factChecks.length>0&&<details className="warning"><summary>책과 확인할 표현</summary>{result.factChecks.map((x,i)=><p key={i}>{x}</p>)}</details>}<button className="primary full" onClick={()=>setStep(2)}>{basicScores?'내 가사 고치기':'추천 가사 살펴보기'}</button></>}</>}
 {step===2&&result&&<><div className="panel-title"><h3>어떤 표현을 살릴까요?</h3><span>03 / 04</span></div>{!basicScores&&<><div className="compare"><div><label>내가 쓴 가사</label><pre>{original}</pre></div><div><label>{basicScores?'기본 점검 · 원문 유지':'AI가 추천한 가사'}</label><pre>{result.revisedLyrics.split('\n').map((line,i)=><span className={original.split('\n').includes(line)?'':'changed'} key={i}>{line||'\u00a0'}{'\n'}</span>)}</pre></div></div><div className="reasons"><h4>이렇게 제안한 이유</h4>{result.reasons.map((r,i)=><p key={i}>{i+1}. {r}</p>)}</div></>}{result.changes.length>0&&<div className="change-list"><h4>표현 하나씩 골라 보기</h4>{result.changes.map((c,i)=><article key={i}><div><del>{c.before||'(새 표현)'}</del><strong>{c.after||'(삭제 제안)'}</strong><p>{c.reason}</p></div><button disabled={!c.before||!final.includes(c.before)} onClick={()=>setFinal(final.replace(c.before,c.after))}>{c.before&&final.includes(c.before)?'적용':'미적용 또는 적용됨'}</button></article>)}</div>}{basicScores&&<p className="caption">바꾸고 싶은 행만 고쳐 보세요. 내 표현을 그대로 살려도 좋아요.</p>}<label className="field-label" htmlFor="draft">내가 선택한 가사 · 자유롭게 수정해요</label><textarea id="draft" value={final} maxLength={3000} onChange={e=>setFinal(e.target.value)}/><div className="actions"><button onClick={()=>{setFinal(original);setMessage('원래 가사를 선택했어요.')}}>원래 가사 유지하기</button><button onClick={()=>{setFinal(result.revisedLyrics);setMessage('AI 추천 가사를 선택했어요.')}}>{basicScores?'원문으로 되돌리기':'AI 추천 가사 사용하기'}</button><button onClick={()=>document.getElementById('draft')?.focus()}>내가 직접 다시 고치기</button></div><div className="actions end"><button onClick={()=>{setLyrics(final);setStep(0);setMessage('수정한 가사로 다시 평가받아 보세요.')}}>다시 평가받기</button><button className="primary" disabled={!final.trim()} onClick={()=>setStep(3)}>이 가사로 완성하기</button></div></>}
 {step===3&&<><div className="panel-title"><h3>나만의 노랫말</h3><span>04 / 04</span></div><div className="complete-label"><Check size={17}/> 나의 선택으로 완성한 노래</div><label htmlFor="final" className="field-label">최종 가사 <span>{final.length} / 3,000자</span></label><textarea id="final" className="final" maxLength={3000} value={final} onChange={e=>setFinal(e.target.value)}/><p className="finish">나만의 노랫말이 완성되었어요!<br/>가사를 복사하고 노래로 만들어 보세요.</p><button className="primary full" disabled={!final.trim()} onClick={copy}><Copy size={18}/> 최종 가사 복사하기</button><a className="suno" href="https://suno.com" target="_blank" rel="noopener noreferrer">Suno에서 노래 만들기 <ExternalLink size={16}/></a><button className="quiet full" onClick={()=>{setLyrics(final);setStep(0)}}>가사 입력으로 돌아가기</button></>}
 </section></div><div className="toast" role="status" aria-live="polite">{message}</div><footer><span>소안도의 노래</span><span>기억은 우리의 목소리로 이어집니다.</span><a href={teacherUrl()}>교사용 안내</a></footer></main>
}
